#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

TOMCAT=tomcat6
TOMCAT_USER=tomcat6
TOMCAT_HOME=/var/lib/tomcat6
APACHE_CONF=/etc/apache2
JK_CONF=onemercury_jk.conf

SOURCE_DIR=/usr/share/dataone-mercury
SCRIPT_DIR=${SOURCE_DIR}/debian


############## 
# Stop tomcat
##############
echo "Stopping Tomcat"
/etc/init.d/${TOMCAT} stop

######################
# Install mercury war
######################
## remove the mercury application directory
if [ -d ${TOMCAT_HOME}/webapps/onemercury ]
then
  echo "Removing the old mercury application directories"
  rm -rf ${TOMCAT_HOME}/webapps/onemercury
fi 

## copy the new war file into the webapps directory
echo "Copying new onemercury.war file to ${TOMCAT_HOME}/webapps/onemercury.war"
cp ${SOURCE_DIR}/onemercury.war ${TOMCAT_HOME}/webapps/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/webapps/onemercury.war

########################
# Configure Tomcat
########################

# Configure the context file
echo "Copying ${SCRIPT_DIR}/onemercury.xml to ${TOMCAT_HOME}/conf/Catalina/localhost/"
cp ${SCRIPT_DIR}/onemercury.xml ${TOMCAT_HOME}/conf/Catalina/localhost/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/Catalina/localhost/onemercury.xml

# Add permissions needed by mercury
echo "Copying ${SCRIPT_DIR}/52mercury.policy to ${TOMCAT_HOME}/conf/policy.d/"
cp ${SCRIPT_DIR}/52onemercury.policy ${TOMCAT_HOME}/conf/policy.d/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/policy.d/52onemercury.policy

###########################
# Configure Apache
###########################

## Stop apache
echo "Stopping Apache"
/etc/init.d/apache2 stop

## copy in jk mount configuration file
echo "Copying ${JK_CONF} site file to ${APACHE_CONF}/jk_mount/"

cp ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/
cp ${SCRIPT_DIR}/rewrite_onemercury ${APACHE_CONF}/conf.d/

##################################
# Start Apache and Tomcat
##################################

## Start Apache
/etc/init.d/apache2 start

## Start Tomcat
echo "starting Tomcat server"
/etc/init.d/${TOMCAT} start

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html
