#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

TOMCAT=tomcat6
TOMCAT_USER=tomcat6
TOMCAT_HOME=/var/lib/tomcat6
APACHE_CONF=/etc/apache2
JK_CONF=mercury3_jk.conf

SOURCE_DIR=/usr/share/portal
SCRIPT_DIR=${SOURCE_DIR}/debian


############## 
Stop tomcat
##############
echo "Stopping Tomcat"
/etc/init.d/${TOMCAT} stop

######################
Install mercury war
######################

## backup the old war file
if [ -e ${TOMCAT_HOME}/webapps/mercury3.war ]
then
  echo "Backing up ${TOMCAT_HOME}/webapps/mercury3.war to ${TOMCAT_HOME}/webapps/mercury3.war.${LONG_DATE}"
  mv ${TOMCAT_HOME}/webapps/mercury3.war ${TOMCAT_HOME}/webapps/mercury3.war.${LONG_DATE}
fi  

## remove the portal application directory
if [ -d ${TOMCAT_HOME}/webapps/mercury3 ]
then
  echo "Removing the old portal application directories"
  rm -rf ${TOMCAT_HOME}/webapps/mercury3
fi 

## copy the new war file into the webapps directory
echo copying new mercury3.war file to ${TOMCAT_HOME}/webapps/mercury3.war
cp ${SOURCE_DIR}/mercury3.war ${TOMCAT_HOME}/webapps/

chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/webapps/mercury3

########################
# Configure Tomcat
########################

# Configure the context file
echo "Copying ${SCRIPT_DIR}/mercury3.xml to ${TOMCAT_HOME}/conf/Catalina/localhost/"
cp ${SCRIPT_DIR}/mercury3.xml ${TOMCAT_HOME}/conf/Catalina/localhost/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/Catalina/localhost/mercury3.xml

# Add permissions needed by portal
echo "Copying ${SCRIPT_DIR}/52mercury.policy to ${TOMCAT_HOME}/conf/policy.d/"
cp ${SCRIPT_DIR}/52mercury.policy ${TOMCAT_HOME}/conf/policy.d/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/policy.d/52mercury.policy

###########################
# Configure Apache
###########################

## Stop apache
echo "Stopping Apache"
/etc/init.d/apache2 stop

## copy in jk mount configuration file
if [ -e ${APACHE_CONF}/jk_mount/${JK_CONF} ]
then 
  JK_DIFF=`diff ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}`
  if [ "${JK_DIFF}" != "" ]
  then
    echo "Backing up ${APACHE_CONF}/jk_mount/${JK_CONF} to ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}"
    mv ${APACHE_CONF}/jk_mount/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}
  fi
fi
echo "Copying ${JK_CONF} site file to ${APACHE_CONF}/jk_mount/"
cp ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/


##################################
# Start Apache and Tomcat
##################################

## Start Apache
/etc/init.d/apache2 start

## Start Tomcat
echo "starting Tomcat server"
/etc/init.d/${TOMCAT} start
