#!/bin/bash

TOMCAT_USER=tomcat7

TOMCAT_HOME=/var/lib/tomcat7
APACHE_CONF=/etc/apache2

/etc/init.d/apache2 stop
/etc/init.d/tomcat7 stop

rm -rf ${TOMCAT_HOME}/webapps/onemercury
rm -f ${TOMCAT_HOME}/webapps/onemercury*
rm -f ${TOMCAT_HOME}/conf/Catalina/localhost/onemercury.xml
rm -f ${TOMCAT_HOME}/conf/policy.d/52onemercury.policy

rm -f ${APACHE_CONF}/jk_mount/onemercury_jk.*
rm -f ${APACHE_CONF}/conf.d/rewrite_onemercury

/etc/init.d/tomcat7 start
/etc/init.d/apache2 start

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html

exit 0
