#!/bin/bash


LONG_DATE=`date +%Y%m%d%H%M%S`
APACHE_CONF=/etc/apache2
TOMCAT=tomcat6
TOMCAT_USER=tomcat6
TOMCAT_BASE=/usr/share/tomcat6
TOMCAT_HOME=/var/lib/tomcat6
SOURCE_DIR=/usr/share/mercury
SCRIPT_DIR=${SOURCE_DIR}/debian
MERCURY_VAR=/var/mercury/mercury_inst/datanet
SOLR_VAR=/var/mercury/solr/datanet
MERCURY_DEV=/var/mercury/mercury_dev/datanet
JK_CONFS="mercury_jk.conf solr_jk.conf"

MERCURY_INSTANCE=mercury3
###############################################################################
#
# Things it would be useful to do in this script
#
# Install mercury3 war file
# Install solr context file
# 
# Install 2 extra needed jar files into tomcat/lib
#
#future tasks:
# Install custom config file(s) for mercury (Mercury3properties.xml, applicationcontext.xml)
#
###############################################################################

## Stop tomcat
echo "Stopping Tomcat"
/etc/init.d/${TOMCAT} stop

chown -R ${TOMCAT_USER}.${TOMCAT_USER} /var/mercury/
#chown -R ${TOMCAT_USER} ${MERCURY_VAR}
#chown -R ${TOMCAT_USER} ${SOLR_VAR}

# Add permissions needed by mercury and solr 
# always overwrite 
cp -f ${SCRIPT_DIR}/52mercury.policy ${TOMCAT_HOME}/conf/policy.d/
cp -f ${SCRIPT_DIR}/53Solr.policy ${TOMCAT_HOME}/conf/policy.d/



## remove the mercury3 application directory
if [ -d ${TOMCAT_HOME}/webapps/mercury3 ]
then
  echo "Removing the old mercury3 application directories"
  rm -rf ${TOMCAT_HOME}/webapps/mercury3
fi 

## copy the new war file into the webapps directory
echo copying new mercury3.war file to ${TOMCAT_HOME}/webapps/mercury3.war
cp -f ${SOURCE_DIR}/mercury3.war ${TOMCAT_HOME}/webapps/mercury3.war

## expand the war file
CURR_DIR=`pwd`

## make mercury3 directory and extract mercury3.war into it.
echo "Making mercury application directory: ${TOMCAT_HOME}/webapps/mercury3"
mkdir ${TOMCAT_HOME}/webapps/mercury3
cd ${TOMCAT_HOME}/webapps/mercury3

echo "extracting mercury3.war into ${TOMCAT_HOME}/webapps/mercury3"
jar -xvf ${TOMCAT_HOME}/webapps/mercury3.war > /dev/null
chown -R ${TOMCAT_USER}.${TOMCAT_USER}  ${TOMCAT_HOME}/webapps/mercury3
echo cd to $CURR_DIR
cd $CURR_DIR

# always overwrite to assure configuration is controlled from the scripts directory
cp -f ${SCRIPT_DIR}/Mercury3Properties.xml ${TOMCAT_HOME}/webapps/mercury3/WEB-INF/classes/Mercury3Properties.xml
cp -f ${SCRIPT_DIR}/applicationContext.xml ${TOMCAT_HOME}/webapps/mercury3/WEB-INF/classes/applicationContext.xml
cp -f ${SCRIPT_DIR}/mercury3.properties ${MERCURY_DEV}/mercury3.properties
cp -f ${SCRIPT_DIR}/googlekey.js ${TOMCAT_HOME}/webapps/${MERCURY_INSTANCE}/scripts/googlekey.js

/etc/init.d/apache2 stop
#
## copy in jk configuration files
for JK_CONF in ${JK_CONFS}
do
    if [ -e ${APACHE_CONF}/jk_mount/${JK_CONF} ]
    then 
      JK_DIFF=`diff ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}`
      if [ "${JK_DIFF}" != "" ]
      then
        echo "Backing up ${APACHE_CONF}/jk_mount/${JK_CONF} to ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}"
        mv ${APACHE_CONF}/jk_mount/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}
      fi
    fi
    echo "Copying ${JK_CONF} site file to ${APACHE_CONF}/jk_mount/"
    cp ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/

done

cp -f ${SCRIPT_DIR}/datanet_solr.xml ${TOMCAT_HOME}/conf/Catalina/localhost/datanet_solr.xml
cp -f ${SOURCE_DIR}/lib/commons-collections-3.2.jar ${TOMCAT_BASE}/lib/commons-collections-3.2.jar
cp -f ${SOURCE_DIR}/lib/mysql-connector-java-3.1.12-bin.jar ${TOMCAT_BASE}/lib/mysql-connector-java-3.1.12-bin.jar
/etc/init.d/tomcat6 start
/etc/init.d/apache2 start

## expand the war file
## here is the kicker update.sh will not work while mercury is still booting up, so sleep for
##  a while like a couple of minutes, while mercury starts up
sleep 120
chmod 750 /var/mercury/mercury_dev/datanet/update.sh
/var/mercury/mercury_dev/datanet/update.sh




