- name: Installing dataone-cn-rest-service
  hosts: dev
  #accelerate: true
  #accelerate_port: 2222
  sudo: true
  tasks:

   - include: routines/pin_packages.yml
   
   - include: packages/dataone-cn-rest-service.yml

