- name: Installing dataone-cn-solr
  hosts: dev
  #accelerate: true
  #accelerate_port: 2222
  sudo: true
  tasks:

   - include: routines/pin_packages.yml
   
   - include: packages/dataone-cn-solr.yml

