- hosts: dev
  #accelerate: true
  #accelerate_port: 2222
  sudo: true
  tasks:
  
    - include: routines/pin_packages.yml
    
    - name: Install the ssl certificates
      action: apt pkg=ssl-cert
      
      
