- include: libaprutil1.yml

- include: libc6.yml

- include: libsybdb5.yml

- name: Installing libaprutil1-dbd-freetds package
  action: apt pkg=libaprutil1-dbd-freetds state=latest install_recommends=no
  register: libaprutil1_dbd_freetds_installed
  when: libaprutil1_dbd_freetds_installed is not defined
