- include: libbsd0.yml

- include: libc6.yml

- include: libncurses5.yml

- name: Installing libedit2 package
  action: apt pkg=libedit2 state=latest install_recommends=no
  register: libedit2_installed
  when: libedit2_installed is not defined
