- include: libc6.yml

- name: Installing libsqlite3-0 package
  action: apt pkg=libsqlite3-0 state=latest install_recommends=no
  register: libsqlite3_0_installed
  when: libsqlite3_0_installed is not defined
