- include: postgresql-8.4.yml

- name: Installing postgresql package
  action: apt pkg=postgresql state=latest install_recommends=no
  register: postgresql_installed
  when: postgresql_installed is not defined
