- include: x11-common.yml

- name: Installing xfonts-encodings package
  action: apt pkg=xfonts-encodings state=latest install_recommends=no
  register: xfonts_encodings_installed
  when: xfonts_encodings_installed is not defined
