- include: dataone-cn-metacat.yml

- include: dataone-cn-os-core.yml

- include: dataone-cn-solr.yml

- include: dataone-cn-version-tool.yml

- include: jsvc.yml

- include: libcommons-daemon-java.yml

- include: sun-java6-jdk.yml

- name: Installing dataone-cn-processdaemon package
  action: apt pkg=dataone-cn-processdaemon state=latest install_recommends=no force=yes
  register: dataone_cn_processdaemon_installed
  when: dataone_cn_processdaemon_installed is not defined
