- include: debconf.yml

- name: Installing debconf-utils package
  action: apt pkg=debconf-utils state=latest install_recommends=no
  register: debconf_utils_installed
  when: debconf_utils_installed is not defined
