- name: Installing default-jre-headless package
  action: apt pkg=default-jre-headless state=latest install_recommends=no
  register: default_jre_headless_installed
  when: default_jre_headless_installed is not defined
