- include: ia32-libs.yml

- include: libc6-i386.yml

- include: sun-java6-jre.yml

- name: Installing ia32-sun-java6-bin package
  action: apt pkg=ia32-sun-java6-bin state=latest install_recommends=no
  register: ia32_sun_java6_bin_installed
  when: ia32_sun_java6_bin_installed is not defined
