- include: debconf.yml

- include: defoma.yml

- include: fontconfig.yml

- name: Installing libpango1.0-common package
  action: apt pkg=libpango1.0-common state=latest install_recommends=no
  register: libpango1_common_installed
  when: libpango1_common_installed is not defined
