- include: libc6.yml

- include: libx11-6.yml

- include: libxext6.yml

- include: libxfixes3.yml

- name: Installing libxcomposite1 package
  action: apt pkg=libxcomposite1 state=latest install_recommends=no
  register: libxcomposite1_installed
  when: libxcomposite1_installed is not defined
