- include: libc6.yml

- include: libx11-6.yml

- include: libxfixes3.yml

- include: libxrender1.yml

- name: Installing libxcursor1 package
  action: apt pkg=libxcursor1 state=latest install_recommends=no
  register: libxcursor1_installed
  when: libxcursor1_installed is not defined
