- name: Installing postgresql-client-common package
  action: apt pkg=postgresql-client-common state=latest install_recommends=no
  register: postgresql_client_common_installed
  when: postgresql_client_common_installed is not defined
