- include: debconf.yml

- include: libfile-copy-recursive-perl.yml

- include: libfile-temp-perl.yml

- name: Installing update-inetd package
  action: apt pkg=update-inetd state=latest install_recommends=no
  register: update_inetd_installed
  when: update_inetd_installed is not defined
