#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

## Stop apache
echo "Start Sychronization with /etc/init.d/mn-synchronize start"
## should only be run after metacat is running and configured
##/etc/init.d/mn-synchronize start





