#!/bin/bash -x

# source the debconf library
if [ -e "/usr/share/debconf/confmodule" ]; then
    . /usr/share/debconf/confmodule
else
    echo "debconf must be installed. Exiting."
    exit 1
fi
# Reminder: don't echo to stdout, it messes up debconf

D1_LOG_DIR=/var/log/dataone
D1_LOG_FILE=dataone-cn-audit-index.debian.log
if [ ! -e ${D1_LOG_DIR} ]; then
    mkdir -p ${D1_LOG_DIR}
    chown tomcat7:tomcat7 ${D1_LOG_DIR}
fi

# functions to echo to STDERR or the install log instead of STDOUT
logError () {
    echo -e "$@" 1>&2
}

log () {
    now=$(date "+%Y-%m-%d %H:%M:%S %Z:")
    echo -e "${now} prerm $@" >> ${D1_LOG_DIR}/${D1_LOG_FILE}
}

SOLR_HOME=/var/solr/home
AUDIT_CORE_NAME=cn-audit
AUDIT_CORE_DIR=${SOLR_HOME}/${AUDIT_CORE_NAME}

ZK_CONF_HOME=/var/lib/zookeeper/conf
APACHE_CONF_HOME=/etc/apache2/conf.d
JETTY_HOME=/var/lib/jetty

log "start"

/etc/init.d/zookeeper stop
/etc/init.d/jetty stop

log "complete"
exit 0
