#!/bin/bash

# Stop jetty
/etc/init.d/jetty stop
update-rc.d -f jetty remove
rm -f /etc/init.d/jetty

# Clean out the jetty init script and defaults
rm -f /etc/init.d/jetty
rm -f /etc/default/jetty
rm -f /var/run/jetty.pid
