- include: dataone-cn-metacat.yml

- include: dataone-cn-os-core.yml

- include: dataone-cn-version-tool.yml

- include: solr-common.yml

- include: solr-tomcat.yml

- include: sun-java6-jdk.yml

- name: Installing dataone-cn-solr package
  action: apt pkg=dataone-cn-solr state=latest install_recommends=no force=yes
  register: dataone_cn_solr_installed
  when: dataone_cn_solr_installed is not defined
