- include: default-jre.yml

- include: openjdk-6-jre.yml

- include: sun-java6-jre.yml

- name: Installing libaccess-bridge-java package
  action: apt pkg=libaccess-bridge-java state=latest install_recommends=no
  register: libaccess_bridge_java_installed
  when: libaccess_bridge_java_installed is not defined
