- include: libaccess-bridge-java.yml

- include: libatk1.0-0.yml

- include: libc6.yml

- include: libcairo2.yml

- include: libfontconfig1.yml

- include: libfreetype6.yml

- include: libglib2.0-0.yml

- include: libgtk2.0-0.yml

- include: libpango1.0-0.yml

- name: Installing libaccess-bridge-java-jni package
  action: apt pkg=libaccess-bridge-java-jni state=latest install_recommends=no
  register: libaccess_bridge_java_jni_installed
  when: libaccess_bridge_java_jni_installed is not defined
