- include: libaprutil1.yml

- include: libc6.yml

- include: libsqlite3-0.yml

- name: Installing libaprutil1-dbd-sqlite3 package
  action: apt pkg=libaprutil1-dbd-sqlite3 state=latest install_recommends=no
  register: libaprutil1_dbd_sqlite3_installed
  when: libaprutil1_dbd_sqlite3_installed is not defined
