- include: libc6.yml

- include: libxcb-render0.yml

- include: libxcb1.yml

- name: Installing libxcb-render-util0 package
  action: apt pkg=libxcb-render-util0 state=latest install_recommends=no
  register: libxcb_render_util0_installed
  when: libxcb_render_util0_installed is not defined
