- include: libc6.yml

- include: libfontconfig1.yml

- include: libfreetype6.yml

- include: libx11-6.yml

- include: libxrender1.yml

- name: Installing libxft2 package
  action: apt pkg=libxft2 state=latest install_recommends=no
  register: libxft2_installed
  when: libxft2_installed is not defined
