- include: libc6.yml

- include: libxau6.yml

- include: libxdmcp6.yml

- name: Installing libxcb1 package
  action: apt pkg=libxcb1 state=latest install_recommends=no
  register: libxcb1_installed
  when: libxcb1_installed is not defined
