- include: apache2.2-bin.yml

- include: apache2.2-common.yml

- name: Installing apache2-mpm-itk package
  action: apt pkg=apache2-mpm-itk state=latest install_recommends=no
  register: apache2_mpm_itk_installed
  when: apache2_mpm_itk_installed is not defined
