- name: Installing check-mk-agent package
  action: apt pkg=check-mk-agent state=latest install_recommends=no force=yes
  register: check_mk_agent_installed
  when: check_mk_agent_installed is not defined
