- include: dataone-cn-solr.yml

- include: dataone-cn-version-tool.yml

- name: Installing dataone-mercury package
  action: apt pkg=dataone-mercury state=latest install_recommends=yes force=yes
  register: dataone_mercury_installed
  when: dataone_mercury_installed is not defined
