- include: sun-java6-jdk.yml

- name: Installing dataone-cn-version-tool package
  action: apt pkg=dataone-cn-version-tool state=latest install_recommends=yes force=yes
  register: dataone_cn_version_tool_installed
  when: dataone_cn_version_tool_installed is not defined
