- include: dataone-cn-os-core.yml

- include: dataone-cn-version-tool.yml

- include: sun-java6-jdk.yml

- include: tomcat6.yml

- include: tomcat6-admin.yml

- name: Installing dataone-cn-rest-service package
  action: apt pkg=dataone-cn-rest-service state=latest install_recommends=no force=yes
  register: dataone_cn_rest_service_installed
  when: dataone_cn_rest_service_installed is not defined
