- include: dataone-cn-metacat.yml

- include: dataone-cn-os-core.yml

- include: dataone-cn-version-tool.yml

- include: solr-common.yml

- include: solr-tomcat.yml

- include: sun-java6-jdk.yml

- name: Installing dataone-cn-solr package
  action: apt pkg=dataone-cn-solr install_recommends=no force=yes
