- include: gsfonts-x11.yml

- include: ttf-bitstream-vera.yml

- include: ttf-dejavu-core.yml

- include: ttf-freefont.yml

- include: ucf.yml

- name: Installing fontconfig-config package
  action: apt pkg=fontconfig-config state=latest install_recommends=no
  register: fontconfig_config_installed
  when: fontconfig_config_installed is not defined
