- name: Installing java5-runtime-headless package
  action: apt pkg=sun-java6-jre state=latest install_recommends=no
  register: java5_runtime_headless_installed
  when: java5_runtime_headless_installed is not defined
