#- include: libc6.yml

#- include: libgnutls26.yml

#- include: libgssapi-krb5-2.yml

- include: libldap-2.4-2.yml

#- include: libsasl2-2.yml

- name: Installing ldap-utils package
  action: apt pkg=ldap-utils state=latest install_recommends=no
  register: ldap_utils_installed
  when: ldap_utils_installed is not defined
