- include: libaprutil1.yml

- include: libc6.yml

- include: libmysqlclient16.yml

- name: Installing libaprutil1-dbd-mysql package
  action: apt pkg=libaprutil1-dbd-mysql state=latest install_recommends=no
  register: libaprutil1_dbd_mysql_installed
  when: libaprutil1_dbd_mysql_installed is not defined
