- include: libaprutil1.yml

- include: libc6.yml

- include: libpq5.yml

- name: Installing libaprutil1-dbd-pgsql package
  action: apt pkg=libaprutil1-dbd-pgsql state=latest install_recommends=no
  register: libaprutil1_dbd_pgsql_installed
  when: libaprutil1_dbd_pgsql_installed is not defined
