- include: default-jre-headless.yml

- include: java2-runtime-headless.yml

- include: libcommons-collections3-java.yml

- include: libcommons-logging-java.yml

- name: Installing libcommons-beanutils-java package
  action: apt pkg=libcommons-beanutils-java install_recommends=no
