- include: default-jre-headless.yml

- include: java2-runtime-headless.yml

- include: libcommons-beanutils-java.yml

- include: libcommons-io-java.yml

- include: libservlet2.5-java.yml

- name: Installing libcommons-fileupload-java package
  action: apt pkg=libcommons-fileupload-java install_recommends=no
