- include: default-jre-headless.yml

- include: java2-runtime-headless.yml

- include: libcommons-codec-java.yml

- include: libcommons-logging-java.yml

- name: Installing libcommons-httpclient-java package
  action: apt pkg=libcommons-httpclient-java state=latest install_recommends=no
  register: libcommons_httpclient_java_installed
  when: libcommons_httpclient_java_installed is not defined
