- include: default-jre-headless.yml

- include: java1-runtime-headless.yml

- include: java2-runtime-headless.yml

- name: Installing libcommons-collections3-java package
  action: apt pkg=libcommons-collections3-java install_recommends=no
