- include: libhtml-parser-perl.yml

- include: libhtml-tagset-perl.yml

- include: perl.yml

- name: Installing libhtml-tree-perl package
  action: apt pkg=libhtml-tree-perl state=latest install_recommends=no
  register: libhtml_tree_perl_installed
  when: libhtml_tree_perl_installed is not defined
