- include: libnet-ssleay-perl.yml

- include: netbase.yml

- include: perl.yml

- name: Installing libio-socket-ssl-perl package
  action: apt pkg=libio-socket-ssl-perl state=latest install_recommends=no
  register: libio_socket_ssl_perl_installed
  when: libio_socket_ssl_perl_installed is not defined
