- include: libc6.yml

- include: libdbus-1-3.yml

- include: libice6.yml

- include: libsm6.yml

- include: libsndfile1.yml

- include: libwrap0.yml

- include: libx11-6.yml

- include: libxtst6.yml

- name: Installing libpulse0 package
  action: apt pkg=libpulse0 state=latest install_recommends=no
  register: libpulse0_installed
  when: libpulse0_installed is not defined
