- include: debconf.yml

- include: libc6.yml

- name: Installing libslp1 package
  action: apt pkg=libslp1 state=latest install_recommends=no
  register: libslp1_installed
  when: libslp1_installed is not defined
