- include: libc6.yml

- include: libice6.yml

- include: libuuid1.yml

- name: Installing libsm6 package
  action: apt pkg=libsm6 state=latest install_recommends=no
  register: libsm6_installed
  when: libsm6_installed is not defined
