- include: libhtml-parser-perl.yml

- include: libhtml-tagset-perl.yml

- include: libhtml-tree-perl.yml

- include: liburi-perl.yml

- include: netbase.yml

- include: perl.yml

- name: Installing libwww-perl package
  action: apt pkg=libwww-perl install_recommends=no
