- include: default-jre-headless.yml

- include: java2-runtime-headless.yml

- name: Installing libxml-commons-external-java package
  action: apt pkg=libxml-commons-external-java install_recommends=no
