- include: libc6.yml

- include: libx11-6.yml

- include: libxext6.yml

- include: libxrender1.yml

- name: Installing libxrandr2 package
  action: apt pkg=libxrandr2 state=latest install_recommends=no
  register: libxrandr2_installed
  when: libxrandr2_installed is not defined
