- include: libbz2-1.0.yml

- include: libc6.yml

- include: libfontenc1.yml

- include: libfreetype6.yml

- include: zlib1g.yml

- name: Installing libxfont1 package
  action: apt pkg=libxfont1 state=latest install_recommends=no
  register: libxfont1_installed
  when: libxfont1_installed is not defined
