- include: libc6.yml

- include: libx11-6.yml

- include: libxext6.yml

- name: Installing libxinerama1 package
  action: apt pkg=libxinerama1 state=latest install_recommends=no
  register: libxinerama1_installed
  when: libxinerama1_installed is not defined
