- include: libc6.yml

- include: libx11-6.yml

- include: libxext6.yml

- name: Installing libxi6 package
  action: apt pkg=libxi6 state=latest install_recommends=no
  register: libxi6_installed
  when: libxi6_installed is not defined
