- include: libc6.yml

- include: libx11-6.yml

- include: libxext6.yml

- include: libxi6.yml

- include: x11-common.yml

- name: Installing libxtst6 package
  action: apt pkg=libxtst6 install_recommends=no
