- include: libc6.yml

- include: libx11-6.yml

- include: libxfixes3.yml

- name: Installing libxdamage1 package
  action: apt pkg=libxdamage1 state=latest install_recommends=no
  register: libxdamage1_installed
  when: libxdamage1_installed is not defined
