- include: iputils-ping.yml

- include: libc6.yml

- include: libssl0.9.8.yml

- include: procps.yml

- include: ucf.yml

- name: Installing nagios-plugins-basic package
  action: apt pkg=nagios-plugins-basic install_recommends=no
