- include: adduser.yml

- include: debconf.yml

- include: lsb-base.yml

- include: postgresql-client-common.yml

- include: procps.yml

- include: ssl-cert.yml

- name: Installing postgresql-common package
  action: apt pkg=postgresql-common install_recommends=no
