- name: Installing python2.6-minimal package
  action: apt pkg=python2.6-minimal state=latest install_recommends=no
  register: python2_minimal_installed
  when: python2_minimal_installed is not defined
