- include: libc6.yml

- include: libltdl7.yml

- include: libreadline6.yml

- include: odbcinst1debian1.yml

- name: Installing unixodbc package
  action: apt pkg=unixodbc state=latest install_recommends=no
  register: unixodbc_installed
  when: unixodbc_installed is not defined
